
[build]
  command = "npm run build:example"
  publish = "exampleSite/public"
  environment = { HUGO_VERSION = "0.116.3" }

[context.production.environment]
  HUGO_VERSION = "0.153.0"
  HUGO_ENV = "production"
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 8888

