
[build]
  command = "npm run build"
  publish = "public"
  base = "."

[context.production.environment]
  HUGO_VERSION = "0.153.0"
  HUGO_ENV = "production"
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 8888

