############# English navigation ##############

# main menu
[[main]]
name = "Data"
url = "/portfolio/"
weight = 1

[[main]]
name = "About"
url = "/about/"
weight = 2

[[main]]
name = "<img src='/images/logonavhome.png' class='h-6 inline'>"
url = "/"
weight = 3

[[main]]
name = "Blog"
url = "/blog/"
weight = 4

[[main]]
name = "Contact"
url = "/contact/"
weight = 5

